/* DELETE 'BankingSystemDB' database*/
DROP SCHEMA IF EXISTS BankingSystemDB;

/* DELETE USER 'user' AT LOCAL SERVER*/
DROP USER IF EXISTS 'spq'@'%';

/* CREATE 'BankingSystemDB' DATABASE */
CREATE SCHEMA BankingSystemDB;

/* CREATE THE USER 'spq' AT LOCAL SERVER WITH PASSWORD 'spq' */
CREATE USER IF NOT EXISTS 'spq'@'%' IDENTIFIED BY 'spq';

/* GRANT FULL ACCESS TO THE DATABASE FOR THE USER 'spq' AT LOCAL SERVER*/
GRANT ALL ON BankingSystemDB.* TO 'spq'@'%';